sequenceDiagram
    actor user as API client
    participant auth as Auth system
    participant user_store as User store
    participant key_management as Key management
    participant key_store as Key store
    participant crypto as Crypto operations
    participant record_management as Record management
    participant record_store as Record store
    participant role_management as Role management
    participant role_store as Role store

    %% User auth workflow
    Note over user,role_store: User authentication workflow
    user->>auth: Register
    activate user
    activate auth
    auth->>user: Send two factor authentication
    auth->>user_store: Store new user credentials
    activate user_store
    deactivate user_store
    auth->>user: Registration success
    deactivate auth
    user->>auth: Login with credentials
    activate auth
    auth->>user_store: Check credentials
    activate user_store
    deactivate user_store
    auth->>user: Send two factor authentication
    auth->>user: Login success
    deactivate auth
    user->>auth: Login
    activate auth
    alt Upon successful login
        key_management->>user: Generate RSA public key
        activate user
        deactivate user
        key_management->>key_store: Generate and store RSA private key
        activate key_store
        deactivate key_store
        activate key_management
    end
    key_management->>key_store: Generate and store AES key
    activate key_store
    deactivate key_store
    deactivate key_management
    deactivate auth
    deactivate user

    %% Record store workflow
    Note over user,role_store: User record store workflow
    user->>record_management: User sends record data to store
    activate user
    activate record_management
    key_management->>crypto: Get user's AES key
    activate crypto
    crypto->>record_management: AES encrypt data
    deactivate crypto
    activate record_management
    deactivate record_management
    role_management->>role_store: Check user role
    activate role_store
    role_management->>record_management: Role authorisation success
    activate record_management
    deactivate record_management
    deactivate role_store
    alt Upon successful role access
        key_management->>record_management: Get RSA public key
        activate record_management
        crypto->>record_management: RSA encrypt data
        deactivate record_management
        activate record_management
        deactivate record_management
        key_management->>record_management: Get RSA private key
        activate record_management
        crypto->>record_management: RSA decrypt
        deactivate record_management
        activate record_management
        deactivate record_management
        record_management->>record_store: Store record
        activate record_store
        record_management->>user: Record store success
        activate user
        deactivate user
        deactivate record_store
        deactivate record_management
    end
    deactivate user

    %% Record retrieve workflow
    Note over user,role_store: User record retrieve workflow
    user->>record_management: User retrieves record
    activate user
    activate record_management
    role_management->>role_store: Check user role
    activate role_store
    role_management->>record_management: Role authorisation success
    activate record_management
    deactivate record_management
    deactivate role_store
    alt Upon successful role access
        key_management->>record_management: Get RSA public key
        activate record_management
        crypto->>record_management: RSA encrypt data
        deactivate record_management
        activate record_management
        deactivate record_management
        key_management->>record_management: Get RSA private key
        activate record_management
        crypto->>record_management: RSA decrypt
        deactivate record_management
        key_management->>record_management: Get user's AES key
        activate record_management
        crypto->>record_management: AES decrypt data
        activate record_management
        deactivate record_management
        deactivate record_management
        record_management->>user: Record retrieve success
        activate user
        deactivate user
    end
    deactivate user
    deactivate record_management

    %% Individual record access workflow
    Note over user,role_store: Individual record access workflow
    user->>record_management: Send data to be stored with access to specific user
    activate user
    activate record_management
    role_management->>role_store: Check user role
    activate role_store
    role_management->>record_management: Role authorisation success
    activate record_management
    deactivate record_management
    deactivate role_store
    alt Upon successful role access
        Note over key_management,record_store: User record store workflow is executed
    end
    record_management->>user: Record store success
    activate user
    deactivate user
    deactivate record_management
    user->>record_management: Wrong user attempts to retrieve record
    activate record_management
    role_management->>role_store: Check user role
    activate role_store
    role_management->>record_management: Wrong user ID and permissions
    activate record_management
    deactivate record_management
    deactivate role_store
    record_management->>user: Role authorisation failed
    activate user
    deactivate user
    deactivate record_management
    user->>record_management: Correct user attempts to retrieve record
    activate record_management
    role_management->>role_store: Check user role
    activate role_store
    role_management->>record_management: Role authorisation success
    activate record_management
    deactivate record_management
    deactivate role_store
    alt Upon successful role access
        Note over user,record_management: User record retrieve workflow is executed
    end
    record_management->>user: Record retrieve success
    activate user
    deactivate user
    deactivate record_management
    deactivate user

    %% Key expiry workflow
    activate user
    Note over user,role_store: Key expiry workflow
    Note over user,key_store: User authentication workflow is executed
    key_management->>crypto: Get user's old AES key
    activate crypto
    crypto->>record_management: AES decrypt data
    activate record_management
    deactivate crypto
    key_management->>key_store: Generate and store new AES key
    activate key_store
    deactivate key_store
    deactivate record_management
    key_management->>crypto: Get user's new AES key
    activate crypto
    crypto->>record_management: AES encrypt data
    activate record_management
    deactivate record_management
    deactivate crypto
    Note over record_management,role_store: User record store workflow is executed
    deactivate user
