name: Docs CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  report_build:
    name: Report .pdf Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g markdownlint-cli

    - name: Install Pandoc and LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        sudo apt-get install -y pandoc-citeproc
        sudo apt-get install -y texlive-xetex

    - name: Install BibTeX
      run: |
        sudo apt-get install -y bibtex2html

    - name: Check Markdown syntax
      run: npx markdownlint '**/*.md' || true

    - name: Check BibTeX syntax
      run: bibtexlint --glob '**/*.bib' || true

    - name: Set timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

    - name: Compile .md to .pdf
      run: |
        timestamp=$(date +"%Y%m%d%H%M%S")
        pandoc docs/report/iss-report.md --filter pandoc-citeproc -o "iss-report-${{ steps.timestamp.outputs.timestamp }}.pdf"

    - name: Upload .pdf artifact
      uses: actions/upload-artifact@v2
      with:
        name: iss-report-artifact
        path: "iss-report-${{ steps.timestamp.outputs.timestamp }}.pdf"

  sequence_diagram_build:
    name: Mermaid Sequence Diagram .png Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install Mermaid
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - name: Convert Mermaid .mmd Diagram File To .svg
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          mmdc -i docs/iss-sequence-diagram.mmd -o "iss-sequence-diagram-${{ steps.timestamp.outputs.timestamp }}.png"

      - name: Upload .png artifact
        uses: actions/upload-artifact@v2
        with:
          name: iss-sequence-diagram-artifact
          path: "iss-sequence-diagram-${{ steps.timestamp.outputs.timestamp }}.png"